### ISSUE TITLE
Design Planning

### ISSUE THREAD

**Issue by steveoni** [systemEng-Learning/postgres-redis#13]
More of design  and analysis issues

## Task

- [ ]  Read chapter 5, 8 and 9 0f Internal Postgress https://www.interdb.jp/pg/index.html
- [ ] Study  redis-postgres synchronization solutions
- [ ] Understand and learn how to create custom background processes in postgres.

**Comment by goodyduru** [comment]
Hey @steveoni, I played around with background processes and shared memory access and got something working. You can check it out in this [experiment branch](https://github.com/systemEng-Learning/postgres-redis/tree/experiment)
