### ISSUE TITLE
Print hello world for specific selected table

### ISSUE THREAD

**Issue by steveoni** [systemEng-Learning/postgres-redis#5]
Currently, the hello world is being printed out for all select and update queries on any kind of Postgres object. Now we want to print it out on a specific table.

## Acceptance

- [x] Print out Hello World on specified tables
- [x] print hello world for a single selected and updated row and not multiple rows.

## task

- [x] do the above for select query
- [x] do the above for update query
